### ISSUE TITLE
yunohost backup create command give me an error

### ISSUE THREAD

**Issue by 6-ril** [YunoHost/moulinette-yunohost#75]
Hello,
When launching this command : 

yunohost backup create

I have the following error : 

Traceback (most recent call last):
File "/usr/bin/yunohost", line 160, in
print_json=PRINT_JSON, use_cache=USE_CACHE)
File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 117, in cli
moulinette.run(args, print_json)
File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 202, in run
ret = self.actionsmap.process(args, timeout=5)
File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 462, in process
return func(**arguments)
File "/usr/lib/moulinette/yunohost/backup.py", line 68, in backup_create
if name in backup_list()['archives']:
File "/usr/lib/moulinette/yunohost/backup.py", line 302, in backup_list
logging.info("unable to iterate over local archives: %s", str(e))
NameError: global name 'logging' is not defined

I'm using version 2.2, that is up to date, installed in a OVH's VPS. THe OS is  debian 7 64bit.

Any idea of what's wrong ?

**Comment by jeromelebleu** [comment]
Thanks for the bug report!

**Comment by 6-ril** [comment]
You're welcome. 
Any idea about when the fix will be deployed ?

**Comment by 6-ril** [comment]
I finally change the file myself, and it's working better. Thanks
